typography_spectrum: 0.8979
color:
  brandColors:
    - '#000000'
    - '#dae4ef'
    - '#463d37'
    - '#a1acc1'
    - '#6f5d4a'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.85547
analytics:
  google: null
  facebook: null
  twitter: null
name: Praha
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Thr Tagline
purpose: []
