name: Praha
favicon: null
layout_spectrum: 0.8147869755048305
typography_spectrum: 0.4086065595038235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5723078423179686
  lightness: 0.6813412795308977
  saturation: 0.202226486755535
  rhythmicContrast: 0.4425046055112034
purpose: []
