name: Praha
favicon: null
layout_spectrum: 0.15236
typography_spectrum: 0.22712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
